INSERT INTO DETALLE VALUES(1, CURRENT_TIMESTAMP() );
INSERT INTO DETALLE VALUES(2, CURRENT_TIMESTAMP() );
INSERT INTO DETALLE VALUES(3, CURRENT_TIMESTAMP() );
INSERT INTO DETALLE VALUES(4, CURRENT_TIMESTAMP() );